import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Memorable Destination",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} style={{
        backgroundColor: "#f9f9f9",
        color: "#333",
        fontFamily: "crimson",
        fontSize: "1rem",
        lineHeight: "1.5",
        margin: "0",
        padding: "0",
        boxSizing: "border-box",
      
      }}>
        
        <div className='flex justify-center'>

        <Header />
        </div>
        {children
        }
        </body>
    </html>
  );
}
